### ISSUE TITLE
Uncaught exception appears

### ISSUE THREAD

**Issue by halilkaya** [gokmen/hodext#4]
Uncaught exception appears when pasting things sometimes.

**A JavaScript error occurred in the main process**
```
Uncaught Exception:
TypeError: Cannot read property 'size' of undefined
    at Timeout.sync [as _onTimeout] (/private/var/folders/nz/vd9hh6yj6yx3h8js16bvv4200000gn/T/AppTranslocation/FA95E1A4-E971-4622-96DA-075537DB46BF/d/Hodext.app/Contents/Resources/app.asar/src/storage.js:40:9)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```

**Comment by gokmen** [comment]
Is there a way to reproduce this? And is this the latest version you are using? I remember a change with the same exact location of the error https://github.com/gokmen/hodext/commit/610e17e79e4e1e7f3eaf495068584952e0f5c0aa#diff-521fe1016845ce06965f02905329ff32 on Jul 3with v0.1.2. If it's not the latest version, can u try with that?

**Comment by halilkaya** [comment]
Sorry, it's my fault. It's fixed in the new version, as you said. I got it fixed after installing the new version. Thanks! 🎉
